//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantXXIDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_SOLICITUD_INSUMO_PRODUCTO_PROVEEDOR
    {
        public ESTADO_SOLICITUD_INSUMO_PRODUCTO_PROVEEDOR()
        {
            this.SOLICITUD_INSUMO_PRODUCTO_PROVEEDOR = new HashSet<SOLICITUD_INSUMO_PRODUCTO_PROVEEDOR>();
        }
    
        public int id_estado_solicitud_insumo_producto_proveedor { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<SOLICITUD_INSUMO_PRODUCTO_PROVEEDOR> SOLICITUD_INSUMO_PRODUCTO_PROVEEDOR { get; set; }
    }
}
