//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantXXIDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESA
    {
        public MESA()
        {
            this.ORDEN = new HashSet<ORDEN>();
        }
    
        public int id_mesa { get; set; }
        public string numero { get; set; }
        public int estado_mesa_id { get; set; }
    
        public virtual ESTADO_MESA ESTADO_MESA { get; set; }
        public virtual ICollection<ORDEN> ORDEN { get; set; }
    }
}
