//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantXXIDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN
    {
        public ORDEN()
        {
            this.RECETA_ORDEN = new HashSet<RECETA_ORDEN>();
        }
    
        public int id_orden { get; set; }
        public int mesa_id { get; set; }
        public string pagada { get; set; }
        public string creado_en { get; set; }
    
        public virtual MESA MESA { get; set; }
        public virtual ICollection<RECETA_ORDEN> RECETA_ORDEN { get; set; }
    }
}
