//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantXXIDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.PRODUCTO_PROVEEDOR = new HashSet<PRODUCTO_PROVEEDOR>();
            this.RECETA_PRODUCTO = new HashSet<RECETA_PRODUCTO>();
        }
    
        public int id_producto { get; set; }
        public string nombre { get; set; }
        public string creado_en { get; set; }
        public string modificado_en { get; set; }
    
        public virtual ICollection<PRODUCTO_PROVEEDOR> PRODUCTO_PROVEEDOR { get; set; }
        public virtual ICollection<RECETA_PRODUCTO> RECETA_PRODUCTO { get; set; }
    }
}
