//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantXXIDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        public RECETA()
        {
            this.RECETA_ORDEN = new HashSet<RECETA_ORDEN>();
            this.RECETA_PRODUCTO = new HashSet<RECETA_PRODUCTO>();
        }
    
        public int id_receta { get; set; }
        public string nombre { get; set; }
        public int precio { get; set; }
        public int usuario_id { get; set; }
        public string creado_en { get; set; }
        public string modificado_en { get; set; }
    
        public virtual ICollection<RECETA_ORDEN> RECETA_ORDEN { get; set; }
        public virtual ICollection<RECETA_PRODUCTO> RECETA_PRODUCTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
