//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantXXIDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public int id_reserva { get; set; }
        public string correo { get; set; }
        public string fecha { get; set; }
        public string hora { get; set; }
        public int comensales { get; set; }
    }
}
