//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantXXIDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_INSUMO_PRODUCTO_PROVEEDOR
    {
        public int id_solicitud_insumo_producto_proveedor { get; set; }
        public int solicitud_insumo_id { get; set; }
        public int producto_proveedor_id { get; set; }
        public int cantidad { get; set; }
        public Nullable<int> recepcion_usuario_id { get; set; }
        public int estado_solicitud_insumo_producto_proveedor_id { get; set; }
        public string observaciones { get; set; }
    
        public virtual ESTADO_SOLICITUD_INSUMO_PRODUCTO_PROVEEDOR ESTADO_SOLICITUD_INSUMO_PRODUCTO_PROVEEDOR { get; set; }
        public virtual PRODUCTO_PROVEEDOR PRODUCTO_PROVEEDOR { get; set; }
        public virtual SOLICITUD_INSUMO SOLICITUD_INSUMO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
