//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantXXIDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.RECETA = new HashSet<RECETA>();
            this.SOLICITUD_INSUMO = new HashSet<SOLICITUD_INSUMO>();
            this.SOLICITUD_INSUMO_PRODUCTO_PROVEEDOR = new HashSet<SOLICITUD_INSUMO_PRODUCTO_PROVEEDOR>();
        }
    
        public int id_usuario { get; set; }
        public string nombres { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string nombre_usuario { get; set; }
        public string contrasenia { get; set; }
        public int rol_id { get; set; }
        public string creado_en { get; set; }
        public string modificado_en { get; set; }
    
        public virtual ICollection<RECETA> RECETA { get; set; }
        public virtual ROL ROL { get; set; }
        public virtual ICollection<SOLICITUD_INSUMO> SOLICITUD_INSUMO { get; set; }
        public virtual ICollection<SOLICITUD_INSUMO_PRODUCTO_PROVEEDOR> SOLICITUD_INSUMO_PRODUCTO_PROVEEDOR { get; set; }
    }
}
